Exclude agent container from being labeled by admission controller
DataDog/helm-charts pull request #1309
Opened 2024-01-31 21:53 UTC by fanny-jiang

#### What this PR does / why we need it:

Exclude the agent container from being labeled when the admission controller is enabled. The agent doesn't send traces and it can be configured to send dogstatsd metrics so it is unnecessary to inject labels into the agent pod. 

This change will also prevent daemonset/agent pod creation problems in GKE Autopilot, which does not allow privileged pod labels to be mutated. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Chart Version bumped
- [X] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [X] `CHANGELOG.md` has been updated
- [ ] Variables are documented in the `README.md`
- [ ] For Datadog Operator chart or value changes update the test baselines (run: `make update-test-baselines`)

2024-01-31 21:57 UTC, clamoriniere reviewed
that was quick 👏 
thanks @fanny-jiang

2024-01-31 21:57 UTC, clamoriniere commented on charts/datadog/templates/daemonset.yaml
> +    {{- if .Values.clusterAgent.admissionController.enabled }}
maybe we dont even needs the `{{- if ...}}` condition since it should have effect on the agent if the admission controller is not enabled

2024-02-01 16:47 UTC, clamoriniere approved these changes

2024-02-01 16:50 UTC, clamoriniere commented
@fanny-jiang the CI job seems to fail on the Daemonset labels

https://github.com/DataDog/helm-charts/actions/runs/7744232710/job/21119084815?pr=1309#step:5:48

2024-02-01 16:50 UTC, clamoriniere commented on charts/datadog/templates/daemonset.yaml
> +    admission.datadoghq.com/enabled: false
```suggestion
    admission.datadoghq.com/enabled: "false"
```

the `false` need to be considered as a string.

2024-02-01 16:51 UTC, clamoriniere requested changes
I forgot about the boolean value issue on yaml

2024-02-01 16:51 UTC, clamoriniere approved these changes

2024-02-01 19:03 UTC, merged

2024-02-22 18:24 UTC, liliyadd commented
Did we add the label in the right place? For the label to be applied to the pods managed by the deployments/daemonset, it needs to be under `spec.template.metadata.labels`. Setting the label under `metadata.labels` only applies it to the deployment/daemonset itself.

2024-02-22 18:35 UTC, liliyadd commented
I have created [this PR](https://github.com/DataDog/helm-charts/pull/1330) that should set the label on pods.