Private root certificates
DataDog/helm-charts pull request #323
Opened 2021-07-20 09:09 UTC by de31a2

#### What this PR does / why we need it:
This PR enables adding additional volumes and volumemounts to add private CA root certificates. / It is needed if the private location needs to check services with a with a private CAs certificate

#### Special notes for your reviewer:
this solution follows the way described in https://docs.datadoghq.com/synthetics/private_locations/configuration/#private-root-certificates

#### Checklist
- [x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [x] Chart Version bumped
- [x] `CHANGELOG.md` has beed updated
- [x] Variables are documented in the `README.md`

2021-09-21 11:46 UTC, de31a2 commented
Rebased onto the current main branch.

2021-11-05 21:12 UTC, brycekahle commented
@de31a2 This PR seems to include a bunch of unrelated commits (31 according to Github). Maybe a fresh rebase is in order?

2021-11-09 08:29 UTC, de31a2 commented
> @de31a2 This PR seems to include a bunch of unrelated commits (31 according to Github). Maybe a fresh rebase is in order?

Yes. I just rebased to a this branch

2021-11-09 11:11 UTC, m-rousse commented
Hi @de31a2,

Looking at the commits, it seems your modifications were doubled, which seem to disturb github a bit:
- ab7d43b, b921f85 and 97d5fbb seems to be very close/almost identical to
- 8c1c867, 3b5731f and c4ff454

I would suggest resetting on `main` and re-applying your changes in your branch to have it in one commit, I would do:
```
git diff origin/main -p > /tmp/patch
git reset --hard origin/main
patch -p0 < /tmp/patch
git commit -m '[synthetics] add private root certificates support'
git push
```

2022-02-01 16:43 UTC, m-rousse commented
Hi @de31a2,

My apologies for not getting back to you about this, I missed the notification when the branch was updated.
I opened a PR on your branch to merge `main` into it and fix conflicts: https://github.com/kiongroup/tdi-datadog-helm-charts/pull/3

Once you've reviewed it/merged it, I'll be ready to approve this one and ask for a merge.

2022-02-02 12:55 UTC, badouralix requested changes
Hi @de31a2, thank you for your contribution. Overall lgtm ! I have added a few nitpicks to fix the linting errors. Would it be possible to take care of them before we go ahead and merge this pull request ?

2022-02-02 12:55 UTC, badouralix commented on charts/synthetics-private-location/CHANGELOG.md
> +* added extra mount (`extraVolumes` and `extraVolumeMounts` ) for supporting private root CA certificates. As described in https://docs.datadoghq.com/synthetics/private_locations/configuration/#priva
```suggestion
* Add extra mount (`extraVolumes` and `extraVolumeMounts`) for supporting private root CA certificates as described in <https://docs.datadoghq.com/synthetics/private_locations/configuration/#private-root-certificates>.
```

2022-02-02 12:55 UTC, badouralix commented on charts/synthetics-private-location/templates/deployment.yaml
> +            {{- end }}
```suggestion
          {{- toYaml .Values.extraVolumeMounts | nindent 10 }}
          {{- end }}
```

2022-02-02 12:55 UTC, badouralix commented on charts/synthetics-private-location/templates/deployment.yaml
> +        {{- end }}
```suggestion
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}
```

2022-02-02 12:55 UTC, badouralix commented on charts/synthetics-private-location/values.yaml
> +# than the content of this CM will be added as files to /etc/datadog/certs/
```suggestion
# Create a ConfigMap containing the PEM files of your custom CA Root certificate
# Then add it as an extra volume mounted on /etc/datadog/certs/
```

2022-07-21 19:04 UTC, closed without merging