System Probe: Remove unknown config key "runtime_security_config.debug"
DataDog/helm-charts pull request #515
Opened 2022-01-12 21:50 UTC by gaffneyd4

#### What this PR does / why we need it:

This PR addresses the following warning log line from the system probe:

```
datadog-zsqjc system-probe 2022-01-12 21:44:20 UTC | SYS-PROBE | WARN | (pkg/util/log/log.go:630 in func1) | Unknown key in config file: runtime_security_config.debug
```

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [ ] Chart Version bumped
- [ ] `CHANGELOG.md` has been updated
- [ ] Variables are documented in the `README.md`

2022-01-12 22:09 UTC, brycekahle approved these changes

2022-01-12 22:22 UTC, clamoriniere requested changes
Hi @gaffneyd4 

Thanks for opening this pull request that improve or agent configuration by removing unused configuration option.
could you follow the pull request description checklist:
 * bump chart version: patch version is enough for this change
 * update the changelog.md file.
 * update the document by running`.github/helm-docs.sh`

Thanks

2022-01-12 23:37 UTC, gaffneyd4 commented
@clamoriniere done! Apologies on not doing so initially. I've seen certain communities leave the versioning to the merger depending on what release version the patch was to be targeted for.

2022-01-12 23:43 UTC, clamoriniere approved these changes
Thanks for you fast pr update

2022-01-22 18:47 UTC, gaffneyd4 commented
Hi @clamoriniere, is this PR ready to be merged?

2022-01-22 19:27 UTC, clamoriniere commented
Looks good, please rebase the branch.

2022-01-26 15:45 UTC, gaffneyd4 commented
@clamoriniere Branch rebased and merge conflicts fixed!

2022-01-26 15:46 UTC, clamoriniere approved these changes

2022-01-26 16:00 UTC, merged