CWS: add network config
DataDog/helm-charts pull request #639
Opened 2022-05-25 13:03 UTC by paulcacheux

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [ ] Chart Version bumped
- [ ] `CHANGELOG.md` has been updated
- [ ] Variables are documented in the `README.md`

2022-05-25 18:59 UTC, buraizu requested changes

2022-05-25 18:59 UTC, buraizu commented on charts/datadog/README.md
> +| datadog.securityAgent.runtime.network.enabled | bool | `false` | Set to true to enable the collection CWS network events |
```suggestion
| datadog.securityAgent.runtime.network.enabled | bool | `false` | Set to true to enable the collection of CWS network events |
```

2022-05-26 07:50 UTC, davidor approved these changes

2022-05-30 07:27 UTC, paulcacheux commented on charts/datadog/README.md
> +| datadog.securityAgent.runtime.network.enabled | bool | `false` | Set to true to enable the collection CWS network events |
Done in last commit

2022-05-30 15:53 UTC, lebauce approved these changes

2022-05-30 23:24 UTC, apigirl approved these changes

2022-05-31 15:03 UTC, merged