[synthetics-private-location] add ability to template config name
DataDog/helm-charts pull request #665
Opened 2022-06-17 01:45 UTC by iorubs

#### What this PR does / why we need it:

Ability to supply a template for the configSecret.
* Reference secrets that were created with a template without having to maintain multiple values files.
* Easier to integrate with external secret providers.

#### Checklist
- [x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [x] Chart Version bumped
- [x] `CHANGELOG.md` has been updated

2022-06-17 08:48 UTC, badouralix requested changes
Hi @iorubs, thanks for your contribution ! Overall lgtm, just added one nitpick

Would to be able to make a similar change for `configConfigMap` a few lines above ?

2022-06-17 08:48 UTC, badouralix commented on charts/synthetics-private-location/CHANGELOG.md
> +* Added ability to template the config secret name.
```suggestion
* Add ability to template the config secret name.
```

2022-06-17 23:37 UTC, iorubs commented on charts/synthetics-private-location/CHANGELOG.md
> +* Added ability to template the config secret name.
Done.

2022-06-17 23:39 UTC, iorubs commented
> Hi @iorubs, thanks for your contribution ! Overall lgtm, just added one nitpick
> 
> Would to be able to make a similar change for `configConfigMap` a few lines above ?

Done.

2022-06-20 11:26 UTC, badouralix approved these changes

2022-06-20 21:37 UTC, iorubs commented
@badouralix one of the checks is timing out, do you have any recommendation on what I should do to fix/rerun it?

2022-06-22 15:16 UTC, badouralix commented
So the chart installation is failing due to the following error, which sort of makes sense since the `synthetics-private-location` chart does not provide the configmap itself and expects it to be created elsewhere

```text
MountVolume.SetUp failed for volume "worker-config" : configmap "config-map-name" not found
```

With the current test setup, creating the configmap/secret before installing the chart is a bit tricky

@iorubs let's remove the new files under `ci/` for now
We will add them back in another pull request once we can handle the configmap/secret creation

2022-06-24 06:09 UTC, iorubs commented
> So the chart installation is failing due to the following error, which sort of makes sense since the `synthetics-private-location` chart does not provide the configmap itself and expects it to be created elsewhere
> 
> ```
> MountVolume.SetUp failed for volume "worker-config" : configmap "config-map-name" not found
> ```
> 
> With the current test setup, creating the configmap/secret before installing the chart is a bit tricky
> 
> @iorubs let's remove the new files under `ci/` for now We will add them back in another pull request once we can handle the configmap/secret creation

That makes sense, thanks.

Done.

2022-06-27 10:26 UTC, badouralix approved these changes

2022-06-27 10:43 UTC, L3n41c approved these changes

2022-06-27 10:47 UTC, merged