Add support for overriding the detected Kubernetes version
DataDog/helm-charts pull request #734
Opened 2022-08-28 14:47 UTC by CmdrSharp

#### What this PR does / why we need it:
This adds the capability to override `.Capabilities.KubeVersion.GitVersion` which makes sure support for Anthos Config Management and Kustomize is maintained.

Not bumping chart version as I don't know if this warrants a new release alone.

#### Which issue this PR fixes
fixes #733 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [ ] Chart Version bumped
- [ ] `CHANGELOG.md` has been updated
- [x] Variables are documented in the `README.md`

2022-08-29 13:39 UTC, maycmlee approved these changes
👍 for docs

2022-09-27 14:04 UTC, CharlyF requested changes
Thank you for this contribution! 
Could you bump the bugfix of the chart version and add an entry to the changelog?
I added some comments, the path of the CRDs needs to match their respective files (it seems like the datadogmetrics was used for all of them).

2022-09-27 14:04 UTC, CharlyF commented on charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml
> +{{- if and .Values.crds.datadogMetrics (semverCompare "<=1.21-0" (include "datadog-crds.kubeVersion" .)) }}
s/datadogMetrics/datadogAgents

2022-09-27 14:04 UTC, CharlyF commented on charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml
> +{{- if and .Values.crds.datadogMetrics (semverCompare "<=1.21-0" (include "datadog-crds.kubeVersion" .)) }}
s/datadogMonitors/datadogAgents

2022-09-27 18:40 UTC, CmdrSharp commented
@CharlyF Good catches! All fixed, and I've bumped the chart version & added a changelog entry as well.

2022-11-24 15:29 UTC, jackwburgess commented
Hello @CharlyF @maycmlee - do we know why these checks where not successful above?

2022-11-28 19:44 UTC, maycmlee commented
> Hello @CharlyF @maycmlee - do we know why these checks where not successful below?

I will defer to @CharlyF on that because I'm not familiar with this repo.

2023-02-21 13:23 UTC, closed without merging