Remove runtime compilation helm config options
DataDog/helm-charts pull request #813
Opened 2022-11-16 18:52 UTC by ISauve

#### What this PR does / why we need it:

Removes `enableKernelHeaderDownload` and `enableRuntimeCompiler` from the helm chart values. These settings should instead be configured via the `DD_ENABLE_KERNEL_HEADER_DOWNLOAD` and `DD_ENABLE_RUNTIME_COMPILER` environment variables.

#### Which issue this PR fixes

Runtime compilation and kernel header downloading are being slowly released to customers. At the current stage of this release, we want these features to be turned off by default for all customers except USM customers. This is achieved by having the system-probe turn on runtime compilation & kernel header downloading when customers have USM enabled, but **only if they haven't explicitly configured these features themselves** (that is, only if these configuration values are not set - see [here](https://github.com/DataDog/datadog-agent/blob/6a3d555a334cfd2dacd7e17c7f9614a2fd22ed28/pkg/network/config/config.go#L324-L332)). We do this so that USM customers have a way to turn off runtime compilation & kernel header downloading if they need to.

When we set default values for runtime compilation & kernel header downloading in the helm charts, the system-probe sees that these configuration values have been set, and so it never enables runtime compilation and kernel header downloading for USM customers. Thus, having default values set in the helm chart is interfering with our rollout of these features.

#### Special notes for your reviewer:

For the purposes of knowing when to mount runtime compilation-related files, we can simply assume runtime compilation is enabled when either the OOM Kill/TCP Queue length checks or service monitoring (USM) is enabled.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [x] Chart Version bumped
- [x] `CHANGELOG.md` has been updated
- [x] Variables are documented in the `README.md`

2022-11-28 16:35 UTC, buraizu approved these changes

2022-11-29 22:16 UTC, CharlyF requested changes
We don't drop fields in minor bumps unfortunately, could you add a deprecation notice instead https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/NOTES.txt#L132?
We will drop them in the next major version (4.0.0).

2022-12-02 16:49 UTC, CharlyF commented
Issue pertains to Kubernetes dropping support of PSP in 1.25. We need to fix this separately 
```
>>> helm install datadog-ji03ar6ktl charts/datadog --namespace datadog-ji03ar6ktl --wait --values charts/datadog/ci/disable-apparmor-values.yaml --timeout 300s
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "datadog-ji03ar6ktl" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

2022-12-05 21:07 UTC, brycekahle approved these changes

2022-12-05 21:34 UTC, merged