Adds securityContext and resources to initContainers for clusterAgent
DataDog/helm-charts pull request #985
Opened 2023-04-03 20:55 UTC by joesteffee

#### What this PR does / why we need it:

Datadog installs are not able to pass a kubeaudit scan due to missing limits and securityContexts on some of the init containers. This allows injection of those parameters

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [x] `CHANGELOG.md` has been updated
- [x] Variables are documented in the `README.md`

2023-04-13 20:59 UTC, fanny-jiang requested changes
Thanks for your contribution! I tested the change in a GKE Autopilot cluster and it seems that it does not support overwriting the default securityContext. I left comments on adding a condition to check for GKE Autopilot. It'd be nice to add a warning for this in the `charts/datadog/templates/NOTES.txt` [file](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/NOTES.txt#L225) in case the config is enabled in GKE Autopilot.

2023-04-13 20:59 UTC, fanny-jiang commented on charts/datadog/templates/_containers-init-linux.yaml
> +{{ include "generate-security-context" (dict "securityContext" .Values.agents.containers.initContainers.securityContext "targetSystem" .Values.targetSystem "seccomp" "" "kubeversion" .Capabilities.Ku
Adding a custom `securityContext` does not seem to be supported in GKE Autopilot. Can you please add a condition here to check if `.Values.providers.gke.autopilot` is not enabled?

```suggestion
{{- if not .Values.providers.gke.autopilot }}
{{ include "generate-security-context" (dict "securityContext" .Values.agents.containers.initContainers.securityContext "targetSystem" .Values.targetSystem "seccomp" "" "kubeversion" .Capabilities.KubeVersion.Version) | indent 2 }}
{{- end }}
```

2023-04-13 20:59 UTC, fanny-jiang commented on charts/datadog/templates/_containers-init-linux.yaml
> +{{ include "generate-security-context" (dict "securityContext" .Values.agents.containers.initContainers.securityContext "targetSystem" .Values.targetSystem "seccomp" "" "kubeversion" .Capabilities.Ku
Here as well

```suggestion
{{- if not .Values.providers.gke.autopilot }}
{{ include "generate-security-context" (dict "securityContext" .Values.agents.containers.initContainers.securityContext "targetSystem" .Values.targetSystem "seccomp" "" "kubeversion" .Capabilities.KubeVersion.Version) | indent 2 }}
{{- end }}
```

2023-04-14 15:52 UTC, fanny-jiang commented
Looks great! One last thing, can you please run `make docs` and push the changes?

2023-04-14 18:22 UTC, fanny-jiang approved these changes

2023-04-17 14:18 UTC, CharlyF approved these changes

2023-04-17 15:30 UTC, merged